---
options:
  tvault-vip:
    type: string
    default: 172.172.1.41
    description: TrilioVault virtual IP Address
  tvault-image-path:
    type: string
    default: /mnt/tvault-appliance-os-3.1.62.qcow2.tar.gz 
    description: TrilioVault Image path & filename
  tvault-hostname:
    type: string
    default: TrilioVM
    description: TrilioVault Hostname
  tvault-num-nodes:
    type: int
    default: 1
    description: TrilioVault number of nodes - accepted values 1 or 3
  tvault-dns:
    type: string
    default: 172.172.1.2
    description: TrilioVault DNS
  tvault-netmask:
    type: string
    default: 255.255.255.0
    description: TrilioVault Netmask
  tvault-gateway:
    type: string
    default: 172.172.1.1
    description: TrilioVault Gateway
  tvault-memory:
    type: int
    default: 6000
    description: TrilioVault VM memory
  tvault-cpu:
    type: int
    default: 4
    description: TrilioVault VM CPUs
  tvault-bridge:
    type: string
    default: br0
    description: Network bridge for TrilioVault
